- name: Harden ESXi Host
  gather_info: no
  hosts: localhost
  strategy: free
  vars:
    cluster_name: "cluster01" 
    esxi_hostname: ""
  tasks:
    - name: Get Services
      vmware_host_service_info:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        cluster_name: "{{ cluster_name }}" 
        validate_certs: no
      tags: debug
    - name: Get Advanced Options
      vmware_host_config_info:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        cluster_name: "{{ cluster_name }}" 
        validate_certs: no
      tags: debug
    - name: Get Firewall Rules
      vmware_host_firewall_info:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        cluster_name: "{{ cluster_name }}" 
        validate_certs: no
      tags: debug
    - name: Set Advanced Options
      vmware_host_config_manager:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        cluster_name: "{{ cluster_name }}" 
        validate_certs: no
        options:
            "UserVars.ESXiShellInteractiveTimeOut": 900
            "UserVars.ESXiShellTimeOut": 900
            "UserVars.DcuiTimeOut": 600
            "UserVars.SuppressShellWarning": 0
            "Security.AccountLockFailures": 3
            "Security.AccountUnlockTime": 900
            "Security.PasswordQualityControl": "similar=deny retry=3 min=disabled,disabled,disabled,disabled,15"
            "DCUI.Access": "root"
            "Net.BlockGuestBPDU": 1
            "Config.HostAgent.plugins.solo.enableMob": false
    - name: Set NTP Service
      vmware_host_service_manager:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        cluster_name: "{{ cluster_name }}" 
        validate_certs: no
        service_name: ntpd
        state: present
        service_policy: on 
      tags: ntp  
    - name: Set SSH Service
      vmware_host_service_manager:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        cluster_name: "{{ cluster_name }}" 
        validate_certs: no
        service_name: TSM-SSH
        state: absent
        service_policy: off  
    - name: Set Shell Service
      vmware_host_service_manager:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        cluster_name: "{{ cluster_name }}" 
        validate_certs: no
        service_name: TSM
        state: absent
        service_policy: off    
    - name: Enable Lockdown Mode
      vmware_host_lockdown:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        cluster_name: "{{ cluster_name }}" 
        validate_certs: no
        state: present  
    - name: Manage general Firewall Rules
      vmware_host_firewall_manager:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        cluster_name: "{{ cluster_name }}"   
        validate_certs: no      
        rules:
        - name: dhcp 
          enabled: False
        - name: DHCPv6
          enabled: False
        - name: iSCSI
          enabled: False
        - name: snmp 
          enabled: False
    - name: Manage NTP Firewall Rules
      vmware_host_firewall_manager:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        cluster_name: "{{ cluster_name }}"   
        validate_certs: no      
        rules:
        - name: ntp
          enabled: True
          allowed_hosts:
            all_ip: False
            ip_address:
            - 192.168.20.10
            - 192.168.20.11
      tags: ntp  
    - name: Set NTP servers
      vmware_host_ntp:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        cluster_name: "{{ cluster_name }}"
        validate_certs: no   
        state: present
        ntp_servers:
        - 192.168.20.10
        - 192.168.20.11
      tags: ntp 


